language: java
jdk: oraclejdk8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install: true
script: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B